### ISSUE TITLE
Proposed enhancement to output structure

### ISSUE THREAD

**Issue by tomharvey** [ADGEfficiency/energy-py-linear#10]
So, the current output is an ordered list of Dicts. In this list, objects [0:-2] describe the periods; the starting charge, the import/export operation throughout the period and so on. Then the final object in the list is largely `null` as it doesn't have import/export throughout the period, and just describes the end state of the battery.

It might be more useful if:

1. The operations and the end state were called out into separate dictionaries
2. The operations were indexed/keyed by the period ID

This would result in something like (some keys removed for brevity, but the structure is there):

``` json
{
    "operations": {
        "0": {
            "Import [MW]": 2.0,
            "Export [MW]": 0.0,
            "Charge [MWh]": 0.0
        },
        "1": {
            "Import [MW]": 0.0,
            "Export [MW]": 2.0,
            "Charge [MWh]": 1.0
        }

    },
    "final-state": {
        "Charge [MWh]": 0.0
    }
}
```

This allows for a more explicit expression of what each part of the output is, and allows for extension of the output without breaking backwards compatibility. For example, the summary could be extended to contain price $/MWh across the whole run, or each operational period could have additional values like DateTimeZone if actual times are being used. Or, the output could also be extended to output something other than a `final-state` and a list of `operations`, maybe confirmation of the Battery config, or ...

The point is, enclosing output into a named dictionary key, allows for this expansion without breaking existing setups.

**Comment by ADGEfficiency** [comment]
Another alternative is to have an `Initial_charge` and `Final_charge` for each time period - this means we can get rid of having anything except `operations`

**Comment by ADGEfficiency** [comment]
See for the fix - https://github.com/ADGEfficiency/energy-py-linear/pull/15
