### ISSUE TITLE
Publish to https://pypi.org

### ISSUE THREAD

**Issue by tomharvey** [ADGEfficiency/energy-py-linear#11]
Just creating a ticket for this task :) 

- [ ] Create a PyPi account
- [ ] Add a LICENSE.txt
- [ ] Add a build system (circleCI or Jenkins)
- [ ] Profit! 🎉 

See https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56 for some guidance.

**Comment by ADGEfficiency** [comment]
Thanks for this - I'm keen for the test suite and API to settle down a bit before we go publishing to pypi - def on my todo list

**Comment by ADGEfficiency** [comment]
@tomharvey - the package is now available through PyPi:

```
$ pip install energypylinear
```

Better late than never :sweat_smile:
