### ISSUE TITLE
Propose a change to the battery efficiency default

### ISSUE THREAD

**Issue by tomharvey** [ADGEfficiency/energy-py-linear#14]
Here https://github.com/ADGEfficiency/energy-py-linear/blob/master/energypylinear/battery/battery.py#L29 the battery is defaulting to a 90% round trip efficiency.

This isn't clear in the docs.

Considering what would be best for quick off-the-shelf use of the library; would a default 100% efficiency be better and/or to make it clear that efficiency is built into the battery model?

**Comment by ADGEfficiency** [comment]
I think make it clear that efficiency is built into the model - which means doc updates?

**Comment by ADGEfficiency** [comment]
I've included the efficiency arg in the readme - see https://github.com/ADGEfficiency/energy-py-linear/commit/39eb86dcf2b5affac822c56eeb1ac30464b1c5bf
