### ISSUE TITLE
Power constraint

### ISSUE THREAD

**Issue by lucas-vivier-cvegroup** [ADGEfficiency/energy-py-linear#17]
I may miss something, but I feel like the power constraint are not considered in the current version.
I would add these constraints:
self.prob += imports[i] <= self.power
self.prob += export[i] - losses[i] <= self.power

**Comment by ADGEfficiency** [comment]
Hello @lucas-vivier-cvegroup - these constraints are in the definition of the import & export variables in [battery.py](https://github.com/ADGEfficiency/energy-py-linear/blob/master/energypylinear/battery/battery.py):

```python
           'imports': LpVariable.dicts(
                'import', idx[:-1], lowBound=0,
                upBound=self.power, cat='Continuous'
            ),

            'exports': LpVariable.dicts(
                'export', idx[:-1], lowBound=0,
                upBound=self.power, cat='Continuous'
            ),
```

The constraints are `upBound=self.power`.
