### ISSUE TITLE
Share code

### ISSUE THREAD

**Issue by peterdudfield** [ADGEfficiency/energy-py-linear#22]
Hi, I just wanted to check if it was ok for me to reference your code on 
https://github.com/openclimatefix/solar-and-storage. 

This is a repo for modelling batteries, using `cxvpy` and has the option of adding a solar panel.

**Comment by ADGEfficiency** [comment]
> Hi, I just wanted to check if it was ok for me to reference your code on https://github.com/openclimatefix/solar-and-storage.
> 
> This is a repo for modelling batteries, using `cxvpy` and has the option of adding a solar panel.

Hi @peterdudfield - this is totally fine, thanks for the shout-out.
