### ISSUE TITLE
Python 3.11 compatibility 

### ISSUE THREAD

**Issue by rzylius** [ADGEfficiency/energy-py-linear#25]
pip install throws with Python 3.11 throws an error:

0.1.0 Requires-Python >=3.10, <3.11

Is the code really dependent on such narrow Python versioning?

**Comment by ADGEfficiency** [comment]
> Is the code really dependent on such narrow Python versioning?

I don't think so - let me have play and I'll push a fix.

**Comment by ADGEfficiency** [comment]
Fixed with https://github.com/ADGEfficiency/energy-py-linear/pull/28
