### ISSUE TITLE
to add minimum SOC of battery

### ISSUE THREAD

**Issue by rzylius** [ADGEfficiency/energy-py-linear#30]
It would be reasonable to add minimum SOC to the battery model, at least with home batteries one is not recommended to fully discharge.

**Comment by ADGEfficiency** [comment]
Hi @rzylius ,

The best way to model this is to just model a smaller battery.

For example, if you have a 2 MWh battery and you want to limit the minimum SOC to not go below 10%, then you would model a 1.8 MWh battery.

What do you think?

**Comment by rzylius** [comment]
sure, this is an easy workarounds solution, probably not worth the effort putting in the library.
