### ISSUE TITLE
SOC not calculated for battery asset

### ISSUE THREAD

**Issue by Minvyd** [ADGEfficiency/energy-py-linear#34]
Hello,

I am trying to calculate battery dispatch simulations for my battery and I notice some problems with the SOC calculations. After carrying out the calculations for yearly data I see that SOC column is always empty. And when I calculate it myself I see that SOC reaches over the batteries maximum capacity. Wouldn't it be best for the battery to work in a daily format? Where the batteries capacity at the end of the day should be at 10% SOC. 

And I have encountered rows where charging and discharging occurs, but if battery is charging at full capacity of the inverter then there is no room for the battery to discharge. (uploading example screenshot) The battery is 4 MWh capacity and the power is 3.2MW initial and final charge variables are set to 0) But in the battery object I input 3.6 MWh capacity, because it is stated by the producers of the battery that it should never reach below 10% SOC levels. So after the calculations I add to the SOC column 0.4 MWh thus achieving full battery charge.

![image](https://github.com/ADGEfficiency/energy-py-linear/assets/112552253/83ebc912-a3f6-484a-8f0b-5759f4ff4456)

**Comment by ADGEfficiency** [comment]
Hi @Minvyd 👋 

Can I grab the dataset and code that you are using?

You can send the data and/or code to adam.green@adgefficiency.com if you want to keep it private.

**Comment by ADGEfficiency** [comment]
This is resolved - @Minvyd was incorrectly re-calculating the SOC (not including losses).

The correct equation is:

```
soc = last_soc + charge - discharge - loss
```
