### ISSUE TITLE
Logger attempts to make directory even if file logging set to false

### ISSUE THREAD

**Issue by ben-freke** [ADGEfficiency/energy-py-linear#48]
I'm running energy-py-linear in a container with a read-only file system. I've noticed that the library fails in a read-only file system because of this section of code:

https://github.com/ADGEfficiency/energy-py-linear/blob/8792ef4ade6678c2ac6b85ed6f517886af7ac0cb/energypylinear/logger.py#L48

### Current Behaviour

When using a read-only file system, the library fails as it attemps to create a directory called `logs` even when `enable_file_logging` is set to false.

### Suggested Fix

Move the `pathlib.Path("logs").mkdir(exist_ok=True)` line into the conditional for `enable_file_logging`.

**Comment by ADGEfficiency** [comment]
@ben-freke - thanks for the PR, appreciated!  Looks like a good change.

Is the file based logging useful to you?

I'm planning to remove it in https://github.com/ADGEfficiency/energy-py-linear/pull/50.

If it's useful I can keep the file based logging in place, but currently I never use it.

**Comment by ben-freke** [comment]
@ADGEfficiency I'm not making use of the file-based logging, but it might be helpful for debugging 🤔 Although I've not got a specific reason to keep the functionality.

I'm using the library in a Lambda on AWS, it's epehemral. I do local dev (where I'd be debugging issues) on my machine so wouldn't have this problem and I'd just use the environment variable - but I've not come across a circumstance where I've needed it.

**Comment by ADGEfficiency** [comment]
Makes sense - Lambda is a good way to use this tool 👍 

Your changes are now deployed to Pypi as version `1.1.1`.

If you feel like it I'd love to know what you are using the library for & what features you'd like to see added - feel free to email me at adam.green@adgefficiency.com if you have the time.
