### ISSUE TITLE
Operation count does not match price periods

### ISSUE THREAD

**Issue by tomharvey** [ADGEfficiency/energy-py-linear#6]
If I input prices of [100, 200] I expect the results to inform me of how the battery should operate in each of these 2 price periods.

Instead, it shows one period of valid import/export instruction and then the end state with summary of end charge and null import/export.

If I add a third price, I get the expected results for the 2 periods and the results are the same regardless of the 3rd price fed into the solver.

**Comment by ADGEfficiency** [comment]
Hi Tom,

This is fixed in [this commit](https://github.com/ADGEfficiency/energy-py-linear/commit/9ca880d2d6a8a898cbc8c7195e94ee49dba9a3f9)

**Comment by tomharvey** [comment]
I'll have a look at that test.

**Comment by tomharvey** [comment]
👍
