### ISSUE TITLE
License

### ISSUE THREAD

**Issue by corneels** [ADGEfficiency/energy-py-linear#68]
I am interested in using this project, but not clear what the license is. Could you add a license? Thank you.

**Comment by ADGEfficiency** [comment]
> I am interested in using this project, but not clear what the license is. Could you add a license? Thank you.

Hi @corneels - I've added a PR with the GNU GPLv3 license - would this fit with your use case?

**Comment by corneels** [comment]
Perfect, thanks.

**Comment by ADGEfficiency** [comment]
> Perfect, thanks.

Great - closed with https://github.com/ADGEfficiency/energy-py-linear/pull/69
