### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tomharvey** [ADGEfficiency/energy-py-linear#9]
I'm now seeing failures in `test_power_capacity_initial_charge()`:

When input params are [2, 4, 0]:
```
(Pdb) gross
[2.0, 2.0, 1.4545455, 2.0, 2.0, 2.0]
(Pdb) net
[2.0, 2.0, 1.60000005, 2.2, 2.0, 2.2]
```

And in `test_batt_efficiency`.

```
E       First has 1, Second has 0:  -1.0
E       First has 0, Second has 1:  -0.33333334000000003
```

Are you seeing failures as well - these are fairly new tests. I'd dig into it, but I think it's in the workings of the solution.

**Comment by ADGEfficiency** [comment]
After I change `calc_net` to `imp - exp + loss` the test suite runs again...

**Comment by ADGEfficiency** [comment]
Closing this - test suite is working fine on master
